---

- name: clone the project

  git:  
    repo: "https://github.com/jtandavala/infrastructure-as-code.git"
    dest: "{{ project_path }}/webapp"
    update: yes
    force: yes
    version: main

- name: give the right privileges
  shell: sudo chown -R $USER:$USER webapp
  args:
    chdir: "{{ project_path }}"

- name: shutdown current version
  shell: docker compose down 
  args:
    chdir: "{{ project_path }}/webapp" 


- name: shutdown current version
  shell: docker compose up -d --build
  args:
    chdir: "{{ project_path }}/webapp" 