---

- name: baixar o unig4construction do gitlab

  git:  

    repo: "https://github.com/tandavala-py/iac.git"

    dest: "{{ project_path }}/webapp"

    update: yes

    force: yes

    version: main