version: "3.8"
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src

    ports:
      - "3000:3000"

    networks:
      - sonarnet

  sonarqube:
    image: sonarqube:10.6-community
    container_name: sonarqube
    ports:
      - "8080:9000" # Expose SonarQube on port 8080
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db
    networks:
      - sonarnet

  db:
    image: postgres:14
    container_name: sonarqube_db
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sonarnet

volumes:
  postgres_data:

networks:
  sonarnet:
