name: Ansible Deploy

on:
  push:
    branches:
      - main  

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['16.x'] 
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install 

      - name: Run tests with Jest
        run: npm run test -- --coverage --ci --testResultsProcessor jest-junit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Set up SSH key
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > iac.pem  # Use GitHub Secrets
          chmod 400 iac.pem  

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False" 
        run: |
          ansible-playbook -i playbook/hosts.ini playbook/playbook.yml --private-key iac.pem
